### ISSUE TITLE
No input reports on Mac

### ISSUE THREAD

**Issue by mhavu** [WICG/webhid#15]
For some reason, I don't get any input report events on Mac. If I try
```javascript
let device = await navigator.hid.getDevices();
device[0].addEventListener('inputreport', async (event) => {
  console.log("Got input report");
});
```
in Chrome 83.0.4103.61, it works on Windows but not on macOS 10.15.4 with the same device. Should there be feature parity between the different OS versions with regard to WebHID implementations?

**Comment by nondebug** [comment]
Make sure you've opened the device:

let devices[0] = await navigator.hid.requestDevice({filters:[]});
await devices[0].open();

I've seen some instances where a device that works on one OS doesn't work on another OS. Usually this is due to errors in the HID report descriptor that misrepresent the size of a report. When the OS receives a report with an unexpected size, it silently drops the report instead of passing it to the application. Please check that the input reports defined in the HID report descriptor match the size of the reports received on Windows.

**Comment by mhavu** [comment]
The device is opened. I can communicate with the device just fine using native code, but input report events don't fire when using WebHID. The device sends 64-byte input reports, and the HID report descriptor states
```
reportCount: 64
reportSize: 8
```
which looks fine to me.

**Comment by nondebug** [comment]
If you're getting input reports in native code but not WebHID that sounds like an implementation bug.

I'm closing this bug since it's not a spec issue. Would you mind creating an issue in the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/entry)? When you do, please identify the HID device you're using.

**Comment by mhavu** [comment]
Thanks. Filed as a Chromium [bug](https://crbug.com/1092625).
