### ISSUE TITLE
Buffer Timing Issue?

### ISSUE THREAD

**Issue by davlovsky** [WICG/webhid#42]
I'm working with a CP2110 USB-to-UART right now.

I can connect to the device, but the input report seems a bit off.
When the device is turned on, it automatically starts spitting out data, but there should always be a 5-byte "Preamble" at the start of the input report, but sometimes the input report is off (shifted).

It works flawlessly in my Winform Desktop App, but for some reason, here it doesn't. 

I've tried adding a slight delay in between reads (200ms, 500ms, 1500ms, etc.) but it doesn't seem to help. 

I might be using this incorrectly, or I don't know if there are other parameters you can set to adjust the input report?

**Comment by nondebug** [comment]
I'm closing this since this appears to be an issue with the Chromium implementation rather than a spec issue. Would you mind opening a new issue in the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/entry)? Please include your javascript code for reading the input report if you're able to share it.

I'm not sure why WebHID would do this, we don't try to adjust the input report buffer received from the OS except to remove the report ID byte.
