### ISSUE TITLE
Does WebHID API to support EP0 getreport like Windows hid API HidD_GetInputReport()? 

### ISSUE THREAD

**Issue by AnyProblem** [WICG/webhid#45]
I do not know how to use WebHID to get report form EP0
Dose it support right now? I only can get report from interrupt (EP1)
Some devices only use control in/out to access

**Comment by nondebug** [comment]
If it isn't working, it's not intentional. The WebHID implementation in Chromium uses ReadFile instead of HidD_GetInputReport as recommended by [Microsoft's documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/obtaining-hid-reports). "If an application attempts to use HidD_GetInputReport to continuously obtain input reports, the reports can be lost. In addition, some devices might not support HidD_GetInputReport, and will become unresponsive if this routine is used."

https://source.chromium.org/chromium/chromium/src/+/master:services/device/hid/hid_connection_win.cc;l=165

I'm closing this because this repo is for spec issues. Implementation bugs should be filed in the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/entry). Please file the bug there with the "Components" field set to IO>HID. If you can, include information about the device(s) you're seeing this issue with.
