### ISSUE TITLE
Collection Dissapear upon disconnect/reconnect

### ISSUE THREAD

**Issue by Raketten1963** [WICG/webhid#51]
Hi all,

Recently I see my collections getting smaller after disconnecting mydevice and then later reconnecting it. 

I made a small test looking like below;

```
navigator.hid.addEventListener('disconnect', ({device}) => {
        console.log(device.collections.length);          //This output 3 on first disconnect, 2 on subsequent
});
navigator.hid.addEventListener('connect', ({device}) => {
        console.log(device.collections.length);          //This always output 2 
});
```
The _missing_ collection is the telephony page 0x0B, my device is a headset.
I am running on Windows. After restart of Canary I am back to 3 collections until first disconnect....

**Comment by jimb456** [comment]
I verify this also.  On Windows only, starting with 89, it appears if headset device is plugged in while Chrome is running, enumerating the collections results in no collection 0xb (the headset collection).  If I kill all Chrome windows, and restart Chrome, enumerating collections results in the expected 0xb re-appearing.  Cannot produce on Mac.  Produced using Jabra 20 but it happens with other headsets.

**Comment by nondebug** [comment]
This is the spec repo, implementation bugs should be filed against Chromium. I created a Chromium bug for this issue: https://crbug.com/1186331

This is a race condition caused by Chrome's attempt to merge HID device nodes that represent top-level collections exposed by the same HID interface. Chrome (incorrectly) assumes that when the deviceAdded event for the first HID device node is received, all the sibling device nodes are already present. If one or more of the device nodes are not present then Chrome fails to discover the HID reports exposed by the delayed nodes. This seems to happen more frequently with the Telephony / Headset device node.

Reading and writing reports should still work even if the collection information is missing.

**Comment by nondebug** [comment]
This should be fixed in Chrome 91:

https://chromiumdash.appspot.com/commit/d61dbac9136e2c62b6162295e1d8106fbd0fe42d
