### ISSUE TITLE
Single headset button press fires event multiple times

### ISSUE THREAD

**Issue by node-one** [WICG/webhid#61]
Hello,

Currently, I am integrating our softphone app with webHID API. It works great but I just noticed that a single headset button press (dial, hangup, etc.) fires same event twice. I've tried testing using Jabra and Plantronics brands, and they both exhibit same behavior with Jabra having an interval of <= 2500 ms and Plantronics with <= 50 ms. I am not sure if this is an expected behavior. If so, is there a way to prevent webHID from firing it multiple times? I just tested two brands and I am worried that same behavior might occur  for other brands as well.  

Also there are times that when a mute button is pressed for Plantronics headsets, multiple events are fired with different report ids which result to an inconsistent behavior. Any comments are highly appreciated. 

Thanks.

**Comment by nondebug** [comment]
> I just noticed that a single headset button press (dial, hangup, etc.) fires same event twice.

I think this is expected. I have a Jabra Engage 50 headset, each time I press the Answer/End Call button I see two reports ~2000 ms apart:

    let devices = await navigator.hid.requestDevice({filters: [{vendorId:0x0b0e}]});
    await devices[0].open();
    devices[0].oninputreport = e => { console.log(e.reportId, new Uint8Array(e.data.buffer); };
    // press and release the Answer/End Call button
    // 1st input report: report ID is 2, report data is Uint8Array(2) [1, 0]
    // 2nd input report: report ID is 2, report data is Uint8Array(2) [0, 0]
    // press and release the Answer/End Call button again after receiving 2nd input report
    // 3rd input report: report ID is 2, report data is Uint8Array(2) [1, 0]
    // 4th input report: report ID is 2, report data is Uint8Array(2) [0, 0]

If I try pressing the button again before the 2nd report is sent I only see three reports:

    // press and release the Answer/End Call button
    // 1st input report: report ID is 2, report data is Uint8Array(2) [1, 0]
    // press and release the Answer/End Call button again within 2000 ms
    // 2nd input report: report ID is 2, report data is Uint8Array(2) [1, 0]
    // 3rd input report: report ID is 2, report data is Uint8Array(2) [0, 0]

From the report descriptor, the first bit of input report 2 has the usage Telephony / Hook Switch and is an Absolute control with No Preferred State. That means the device should send a 1 when the headset is "off-hook" and a 0 when it is "on-hook".

I also tried a Logitech Stereo H650e headset which has slightly different behavior. Input report 8, bit 2 has usage Telephony / Hook Switch.

    // press and release the Answer/End Call button
    // 1st input report: report ID is 8, report data is Uint8Array [2]
    // press and release the Answer/End Call button again
    // 2nd input report: report ID is 8, report data is Uint8Array [0]
    // 3rd input report: report ID is 8, report data is Uint8Array [2]

On the first press, the Logitech headset sends a single report with the "off-hook" signal. Unlike the Jabra headset, it stays in "off-hook" state indefinitely. When the button is pressed again, the headset sends an "on-hook" followed quickly (<10ms) by another "off-hook". Maybe this is similar to the Plantronics device behavior?

I think the headset is trying to pick up a call that doesn't exist. In the normal case, the softphone app should have responded with an LED / Off-hook signal to indicate that the call was answered.

Jabra publishes a [HID specification](https://developer.jabra.com/site/global/sdks/web/documentation/index.gsp) for their headsets which may be useful to you. I don't see this particular case described anywhere but there are a number of other examples. I haven't found anything similar for Plantronics/Poly.

> Also there are times that when a mute button is pressed for Plantronics headsets, multiple events are fired with different report ids which result to an inconsistent behavior.

I'm guessing one of the reports is using vendor-defined usages. HID Telephony devices are troublesome because the device holds state that must be kept in sync with the softphone app, but the operating system doesn't provide reliable ways to mediate access to the device when there are multiple softphone apps trying to access the same headset. One strategy is to provide parallel implementations of the telephony signals: one with the standard usages from the Telephony and LED usage pages, and another with vendor-defined usages. In the default mode, the device will respond to standard HID signals or vendor-defined signals. When the headset receives the vendor-defined signals, it places itself into a mode where it stops responding to standard HID signals.
